# Generated by Django 4.2.4 on 2023-08-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
