# Generated by Django 4.2.4 on 2023-08-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='User',
        ),
    ]
